#!/usr/bin/env bash

# Install Nginx and the init file have only a message
sudo apt-get update -y
sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to a github 
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/abdessamad-el-majdouly permanent;"
sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default


# Setting up a 404 page
echo "Ceci n'est pas une page"  | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\tinternal;\n\t}"
sudo sed -i "s#listen 80 default_server;#$string_for_replacement#" /etc/nginx/sites-enabled/default


# Restarting nginx
sudo service nginx restart
