#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#
# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
sudo apt-get update
sudo apt-get install nginx -y

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

#  Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to a github 
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/abdessamad-el-majdouly permanent;"

sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

# Creating a 404 page
echo " Ceci n'est pas une page " | sudo tee /var/www/html/404.html

# Setting up a 404 page 
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\tinternal;\n\t}"

sudo sed -i "s#listen 80 default_server;#$string_for_replacement#" /etc/nginx/sites-enabled/default

#custom HTTP response header
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test for syntax erros
sudo nginx -t

# Restarting nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅ \n"
~                                              
