#!/bin/bash

# Get the parent directory of the working directory
parent_dir=$(dirname $(pwd))

# Copy all HTML files to the parent directory, only if they are newer or don't exist
find . -maxdepth 1 -name '*.html' -type f -newer "$parent_dir" -exec cp -n {} "$parent_dir" \;
