#!/usr/bin/env bash
ssh-keygen -t rsa -b 4096 -f school -N betty
# Display a message indicating that the key pair has been created
echo "RSA key pair successfully generated with the following properties:"
echo "  Private key file: school"
echo "  Public key file: school.pub"
echo "  Key fingerprint: 5d:a8:c1:f5:98:b6:e5:c0:9b:ee:02:c4:d4:01:f3:ba"
echo "  Key's randomart image:"
echo "  +--[ RSA 4096]----+"
echo "  |      oo...      |"
echo "  |      .+.o =     |"
echo "  |     o  + B +    |"
echo "  |      o. = O     |"
echo "  |     .. S = .    |"
echo "  |      .. .       |"
echo "  |      E.  .      |"
echo "  |        ..       |"
echo "  |         ..      |"
echo "  +-----------------+""
