#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.158.80.87
    HostName 54.205.163.79
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
