#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
# Configure ssh client so that you can connect to a server without typing a password.
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
